baseURL = "https://simongrund1.github.io/"
languageCode = "en-us"
title = "Simon Grund"
googleAnalytics = "my-ga"
DisqusShortname = "my-shortname"
theme = "hyde"

[params]
description = "PhD, Quantitative Psychology"
themeColor = "theme-base-00"
summaryLength = 275
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[menu]
  [[menu.main]]
  identifier = "posts"
  name       = "Blog"
  url        = "/posts"
  weight     = 1

  [[menu.main]]
  identifier = "publications"
  name       = "Publications"
  url        = "/publications/"
  weight     = 2

  [[menu.main]]
  identifier = "software"
  name       = "Software"
  url        = "/software/"
  weight     = 3
